In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.formula.api as smf

## data load in

In [15]:
path = "Data/gas_coordinates.csv"
gas = pd.read_csv(path)
gas["date"] = pd.to_datetime(gas["date"])
gas["month"] = gas["date"].dt.month

gas.head()

,metro,date,regular,mid,premium,diesel,reg_delt,met,lat,lng,month
0,Bradenton-Sarasota-Venice,2022-01-21,3.236000,3.625,3.915000,3.563000,NaN,North Port-Bradenton-Sarasota,27.3479,-82.3223,1
1,Bradenton-Sarasota-Venice,2022-01-22,3.254667,3.639,3.929667,3.587667,0.576844,North Port-Bradenton-Sarasota,27.3479,-82.3223,1
2,Bradenton-Sarasota-Venice,2022-01-23,3.273333,3.653,3.944333,3.612333,0.573535,North Port-Bradenton-Sarasota,27.3479,-82.3223,1
3,Bradenton-Sarasota-Venice,2022-01-24,3.292000,3.667,3.959000,3.637000,0.570265,North Port-Bradenton-Sarasota,27.3479,-82.3223,1
4,Bradenton-Sarasota-Venice,2022-01-25,3.310667,3.681,3.973667,3.661667,0.567031,North Port-Bradenton-Sarasota,27.3479,-82.3223,1

In [25]:
path = "Data/ignore/hurr_mod.csv"
hurricanes = pd.read_csv(path)
hurricanes["date"] = pd.to_datetime(hurricanes["DATE"])

## combining

In [26]:
gas['date'].dtype == hurricanes['date'].dtype

True

In [20]:
hurricanes.isna().sum()

SID                  0
SEASON               0
NAME                 0
MAX CAT              0
START DATE           0
END DATE             0
STORM DURATION       0
ISO_TIME             0
NATURE               0
DIST2LAND            0
LANDFALL            32
USA_LAT              0
USA_LON              0
USA_RECORD           0
USA_STATUS           0
USA_WIND             0
USA_PRES             0
USA_SSHS             0
USA_POCI             6
USA_ROCI             6
USA_RMW              0
USA_EYE           2624
USA_GUST             0
USA_SEAHGT        1012
STORM_SPEED          0
STORM_DIR            0
DATE                 0
dtype: int64

distance with euclidean measure

In [21]:
hurricanes.shape

(2661, 27)

In [27]:
hurricanes = hurricanes.drop_duplicates(subset = "date", keep = "first")
hurricanes.shape

(254, 28)

In [24]:
gas.shape

(34560, 11)

In [28]:
panel = gas.merge(hurricanes, on = "date", how = "left")
panel.shape

(34560, 38)

In [30]:
panel.head()

,metro,date,regular,mid,premium,diesel,reg_delt,met,lat,lng,...,USA_SSHS,USA_POCI,USA_ROCI,USA_RMW,USA_EYE,USA_GUST,USA_SEAHGT,STORM_SPEED,STORM_DIR,DATE
0,Bradenton-Sarasota-Venice,2022-01-21,3.236000,3.625,3.915000,3.563000,NaN,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bradenton-Sarasota-Venice,2022-01-22,3.254667,3.639,3.929667,3.587667,0.576844,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bradenton-Sarasota-Venice,2022-01-23,3.273333,3.653,3.944333,3.612333,0.573535,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bradenton-Sarasota-Venice,2022-01-24,3.292000,3.667,3.959000,3.637000,0.570265,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bradenton-Sarasota-Venice,2022-01-25,3.310667,3.681,3.973667,3.661667,0.567031,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
hurricanes.columns

Index(['SID', 'SEASON', 'NAME', 'MAX CAT', 'START DATE', 'END DATE',
       'STORM DURATION', 'ISO_TIME', 'NATURE', 'DIST2LAND', 'LANDFALL',
       'USA_LAT', 'USA_LON', 'USA_RECORD', 'USA_STATUS', 'USA_WIND',
       'USA_PRES', 'USA_SSHS', 'USA_POCI', 'USA_ROCI', 'USA_RMW', 'USA_EYE',
       'USA_GUST', 'USA_SEAHGT', 'STORM_SPEED', 'STORM_DIR', 'DATE', 'date'],
      dtype='str')

In [37]:
print("gas:", gas.shape)
print("hurricanes:", hurricanes.shape)
print("panel:", panel.shape)

panel[["date", "met", "lat", "lng", "USA_LAT", "USA_LON"]].head(10)

gas: (34560, 11)
hurricanes: (254, 28)
panel: (34560, 38)

,date,met,lat,lng,USA_LAT,USA_LON
0,2022-01-21,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
1,2022-01-22,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
2,2022-01-23,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
3,2022-01-24,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
4,2022-01-25,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
5,2022-01-26,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
6,2022-01-27,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
7,2022-01-28,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
8,2022-01-29,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN
9,2022-01-30,North Port-Bradenton-Sarasota,27.3479,-82.3223,NaN,NaN

In [40]:
panel["distance"] = np.sqrt(
    (panel["lat"] - panel['USA_LAT'])**2 + 
    (panel["lng"] - panel['USA_LON'])**2
)

In [41]:
panel.head()

,metro,date,regular,mid,premium,diesel,reg_delt,met,lat,lng,...,USA_POCI,USA_ROCI,USA_RMW,USA_EYE,USA_GUST,USA_SEAHGT,STORM_SPEED,STORM_DIR,DATE,distance
0,Bradenton-Sarasota-Venice,2022-01-21,3.236000,3.625,3.915000,3.563000,NaN,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bradenton-Sarasota-Venice,2022-01-22,3.254667,3.639,3.929667,3.587667,0.576844,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bradenton-Sarasota-Venice,2022-01-23,3.273333,3.653,3.944333,3.612333,0.573535,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bradenton-Sarasota-Venice,2022-01-24,3.292000,3.667,3.959000,3.637000,0.570265,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bradenton-Sarasota-Venice,2022-01-25,3.310667,3.681,3.973667,3.661667,0.567031,North Port-Bradenton-Sarasota,27.3479,-82.3223,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
panel.to_csv("../Data/ignore/panel_data.csv", index = False)